server:
  port: 9003

spring:
  datasource:
    url: jdbc:mysql://120.26.142.247:3306/spring_security?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  main:
    # 允许我们自己覆盖spring放入ioc容器的对象
    allow-bean-definition-overriding: true


# mybatis-plus 相关配置
mybatis-plus:
  # MyBatis 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.iotmars.po
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法
  mapper-locations: classpath:/mapper/*Mapper.xml
  # 驼峰
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.iotmars: debug